### PR TITLE
fix(transform): do not throw on nullish value

### LINKED ISSUE #18: TypeError: Cannot read property 'prototype' of null at carehtml.js:57
## What we do

We embed a `null` or `undefined` expression any place within the template literal, e.g.

> Example 1
```js
html`<p>${null}</p>`;
```
> Example 2
```js
html`<p someattribute=${undefined}></p>`
```

## What we expect to happen

In both cases `html` should render `<p></p>`.

## What actually happens

> Example 1
```
Uncaught (in promise) TypeError: Cannot read property 'prototype' of null
    at carehtml.js:57
    at Array.forEach (<anonymous>)
    at transform (carehtml.js:55)
    at carehtml.js:83
```

> Example 2
```
Uncaught (in promise) TypeError: Cannot read property 'prototype' of undefined
    at carehtml.js:57
    at Array.forEach (<anonymous>)
    at transform (carehtml.js:55)
    at carehtml.js:83
```

### PR DESCRIPTION
**Pull request by c-dinkel**
This closes #18 by checking for a falsey `value` in `transform` before checking `value.prototype instanceof HTMLElement`, thereby also excluding nullish values. Since no `HTMLElement` is ever falsey, this will never exclude a needed value by mistake.

### CODE REVIEW

File: src/transform.js [hunk 1]
```diff
@@ -54,7 +54,7 @@ export default function transform(strings, values) {
   let mergeWithLastString = false;
   values.forEach((value, index) => {
     const string = strings[index];
-    if (value.prototype instanceof HTMLElement) {
+    if (value && value.prototype instanceof HTMLElement) {
```
Comment (bashmish) [inline src/transform.js:57]: LGTM, good find!

File: test/wrap.spec.js [hunk 2]
```diff
@@ -11,9 +11,10 @@ describe('wrap', () => {
     });
     class MyLily extends HTMLElement {}
 
-    html`<${MyLily} id="${'my-id'}">${'my text'}</${MyLily}>`;
+    html`<${MyLily} id="${'my-id'}" style=${null}>${'my text'}</${MyLily}>`;
+    console.warn(calledArgs);
     expect(calledCount).to.equal(1);
-    expect(calledArgs).to.deep.equal([['<my-lily id="', '">', '</my-lily>'], 'my-id', 'my text']);
+    expect(calledArgs).to.deep.equal([['<my-lily id="', '" style=', '>', '</my-lily>'], 'my-id', null, 'my text']);
```
Comment (bashmish) [inline test/wrap.spec.js:17]: this logic belongs to "src/transform.js" and is better to test in "test/transform.spec.js"

I'd suggest to write a new test after this one, e.g. `it('does not throw on nullish value')`, and provide all sort of nullish values that you are interested in,  one test is OK

```
  it('registers names for Custom Element classes in values and concatenates strings with those names', () => {
    class MyTulip extends HTMLElement {}
    const [strings, ...values] = transform(...testhtml`<${MyTulip} id="${'my-id'}">${'my text'}</${MyTulip}>`);
    expect(strings).to.deep.equal(['<my-tulip id="', '">', '</my-tulip>']);
    expect(values).to.deep.equal(['my-id', 'my text']);
    expect(customElements.get('my-tulip')).to.equal(MyTulip);
  });
```

**Review by bashmish — CHANGES_REQUESTED** [review]
Given this is a change in "transform.js" and the test is in the corresponding file, I think it's logical to merge 2 commits in one under the same name as the PR title suggests "fix(transform): do not throw on nullish value".

File: test/wrap.spec.js (hunk 2 above)
Comment (c-dinkel) [reply test/wrap.spec.js]: Done, thanks for your patience 🌞

File: src/transform.js (hunk 1 above)
Comment (c-dinkel) [reply src/transform.js:57]: Good idea, this will automatically happen if you "Squash commits" upon merging the pull requests.

**Comment by c-dinkel** [comment]
> Given this is a change in "transform.js" and the test is in the corresponding file, I think it's logical to merge 2 commits in one under the same name as the PR title suggests "fix(transform): do not throw on nullish value".

Good idea, this is what github will automatically do if you choose "Squash commits" upon merging the pull request.

**Review by bashmish — APPROVED** [review]
good to be merged now, thanks!

**Comment by bashmish** [comment]
Released in https://www.npmjs.com/package/carehtml/v/0.1.2
